# Generated by Django 5.1.3 on 2024-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('monthly_salary', models.FloatField()),
                ('phone_number', models.IntegerField(max_length=15)),
                ('approved_limit', models.FloatField(blank=True, null=True)),
                ('current_debt', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
