# Generated by Django 5.1.3 on 2024-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_paid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
