# Generated by Django 5.1.3 on 2024-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_loan_emi_paid_alter_loan_monthly_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
